/**
 * PhiClaw Orchestrator — Core Types
 *
 * Defines the data structures for orchestration plans, tasks,
 * execution results, and configuration.
 */

// ─── Task Types ────────────────────────────────────────────

export type TaskStatus = "pending" | "running" | "completed" | "failed" | "skipped";

export type ExecutionMode = "sequential" | "parallel" | "mixed";

/**
 * A single unit of work within an orchestration plan.
 */
export interface Task {
  /** Unique task identifier (e.g. "task-1", "task-2") */
  id: string;
  /** Human-readable task description */
  description: string;
  /** IDs of agents assigned to this task */
  assignedAgents: string[];
  /** IDs of tasks that must complete before this one starts */
  dependencies: string[];
  /** Current execution status */
  status: TaskStatus;
  /** Prompt to send to the agent(s) for this task */
  prompt: string;
  /** Result text after completion */
  result?: string;
  /** Error message if failed */
  error?: string;
  /** Execution metrics */
  metrics?: TaskMetrics;
  /** Number of retry attempts made */
  retryCount: number;
  /** Maximum retries allowed */
  maxRetries: number;
}

/**
 * Metrics collected during task execution.
 */
export interface TaskMetrics {
  /** Wall-clock time in milliseconds */
  durationMs: number;
  /** Timestamp when task started */
  startedAt: string;
  /** Timestamp when task completed/failed */
  completedAt: string;
  /** Number of agents that contributed */
  agentsUsed: number;
}

// ─── Plan Types ────────────────────────────────────────────

/**
 * A complete orchestration plan generated by the Planner.
 */
export interface OrchestrationPlan {
  /** Unique plan identifier */
  id: string;
  /** Original user objective */
  objective: string;
  /** Ordered list of tasks to execute */
  tasks: Task[];
  /** Suggested execution mode */
  executionMode: ExecutionMode;
  /** Human-readable estimated duration */
  estimatedDuration: string;
  /** IDs of all required agents */
  requiredAgents: string[];
  /** Timestamp when plan was created */
  createdAt: string;
}

// ─── Execution Result Types ────────────────────────────────

/**
 * The final result of an orchestration execution.
 */
export interface OrchestrationResult {
  /** Plan that was executed */
  plan: OrchestrationPlan;
  /** Overall status */
  status: "completed" | "partial" | "failed";
  /** Compiled final deliverable */
  deliverable: string;
  /** Summary of execution */
  summary: string;
  /** Total execution time in milliseconds */
  totalDurationMs: number;
  /** Individual task results */
  taskResults: TaskResult[];
  /** Timestamp when execution completed */
  completedAt: string;
}

/**
 * Result of a single task execution.
 */
export interface TaskResult {
  taskId: string;
  taskDescription: string;
  agentNames: string[];
  status: TaskStatus;
  result: string;
  error?: string;
  durationMs: number;
}

// ─── Configuration Types ───────────────────────────────────

/**
 * Orchestrator configuration (from openclaw.json).
 */
export interface OrchestratorConfig {
  /** Whether the orchestrator is enabled */
  enabled: boolean;
  /** Maximum number of tasks that can run concurrently */
  maxConcurrentTasks: number;
  /** Default LLM model for orchestration */
  defaultModel: string;
  /** Whether to show the plan before executing */
  planBeforeExecute: boolean;
  /** Maximum number of tasks per plan */
  maxTasksPerPlan: number;
  /** Maximum retries per task */
  maxRetriesPerTask: number;
  /** Timeout per task in milliseconds */
  taskTimeoutMs: number;
}

/**
 * Agent directory configuration.
 */
export interface AgentDirectoryConfig {
  /** Path to agents directory */
  directory: string;
  /** Which divisions to enable ("all" or specific names) */
  enabledDivisions: string[];
  /** Agent IDs to explicitly disable */
  disabledAgents: string[];
  /** Path to custom agents directory */
  customAgentsDirectory: string;
}

/**
 * Default orchestrator configuration values.
 */
export const DEFAULT_ORCHESTRATOR_CONFIG: OrchestratorConfig = {
  enabled: true,
  maxConcurrentTasks: 4,
  defaultModel: "anthropic/claude-sonnet-4-20250514",
  planBeforeExecute: true,
  maxTasksPerPlan: 10,
  maxRetriesPerTask: 2,
  taskTimeoutMs: 120_000,
};

/**
 * Default agent directory configuration values.
 */
export const DEFAULT_AGENT_DIR_CONFIG: AgentDirectoryConfig = {
  directory: "./agents",
  enabledDivisions: ["all"],
  disabledAgents: [],
  customAgentsDirectory: "./custom-agents",
};

// ─── Event Types (for progress reporting) ──────────────────

export type OrchestratorEventType =
  | "plan-created"
  | "task-started"
  | "task-completed"
  | "task-failed"
  | "task-retrying"
  | "execution-completed"
  | "execution-failed";

export interface OrchestratorEvent {
  type: OrchestratorEventType;
  timestamp: string;
  planId: string;
  taskId?: string;
  message: string;
  data?: Record<string, unknown>;
}

export type OrchestratorEventHandler = (event: OrchestratorEvent) => void;
